[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "git"]
aptPkgs = ["git"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start" 