[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]
aptPkgs = ["git"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
watchPatterns = ["./"] 