[phases.setup]
nixPkgs = ["nodejs-18_x"]
aptPkgs = []

[phases.install]
cmds = ["npm ci --legacy-peer-deps --prefer-offline"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start" 