[build]
builder = "nixpacks"
buildCommand = "npm run build"
cache = ["node_modules"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
numReplicas = 1

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true" 