[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"

[variables]
NODE_ENV = "production"
PORT = "3000"
RAILWAY_DOCKERFILE_PATH = "./Dockerfile" 